package lexer;

public enum TokenType {
    PERCENT, RIGHT_PAREN, STAR, PLUS, COMMA,
    MINUS, DOT, SLASH, LESS, ASSIGNMENT,
    GREATER, LEFT_SQUARE_BRACE, RIGHT_SQUARE_BRACE, LEFT_BRACE, RIGHT_BRACE,
    DOT_DOT, NOT_EQUAL, LESS_EQUAL, EQUAL, GREATER_EQUAL,
    OR, AND, TYPE_INT, XOR, TYPE_DOUBLE, DOUBLE,
    TYPE_STRING, TYPE_BOOLEAN, FUNCTION, IDENTIFIER, END, IS, LEFT_PAREN,
    RETURN, INTEGER, COLON, EQUAl_EQUAL, VAR, SLASH_EQUAL, SEMICOLON,
    TYPE_RECORD, TYPE_ARRAY, ARRAY, BOOLEAN, ELSE,
    FALSE, FOR, IF, IN, LOOP, NOT, PRINT, REAL,
    RECORD, REVERSE, THEN, TRUE, TYPE, WHILE, STRING, EOF
}
